export const MOCK_NP_DATA = [
  {
    id: 1, source: 'Cleaned_Proteins_Regression',
    mod_type: 'No Modification', mod_charge: 'No Modification',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '100~150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_time_group: '30~60',
    shaking: 'Y', washing_step_count: '4~6',
    'Apolipoprotein A-I': 11.23, 'Complement C3': 1.09,
    'Apolipoprotein E': 5.19, 'Serum albumin': 1.31,
    'Clusterin': 0.24, 'Vitronectin': 1.39,
    'Histidine-rich glycoprotein': 10.31, 'Fibrinogen alpha chain': 0.37,
  },
  {
    id: 2, source: 'Cleaned_Proteins_Regression',
    mod_type: 'No Modification', mod_charge: 'No Modification',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '>150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_time_group: '30~60',
    shaking: 'Y', washing_step_count: '4~6',
    'Apolipoprotein A-I': 7.17, 'Complement C3': 1.14,
    'Apolipoprotein E': 2.97, 'Serum albumin': 2.39,
    'Clusterin': 0.45, 'Vitronectin': 0.90,
    'Histidine-rich glycoprotein': 17.51, 'Fibrinogen alpha chain': 0.49,
  },
  {
    id: 3, source: 'Cleaned_Proteins_Regression',
    mod_type: 'Amines', mod_charge: 'Positive',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '100~150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_time_group: '30~60',
    shaking: 'Y', washing_step_count: '4~6',
    'Apolipoprotein A-I': 3.77, 'Complement C3': 1.22,
    'Apolipoprotein E': 3.05, 'Serum albumin': 1.16,
    'Clusterin': 0.23, 'Vitronectin': 1.86,
    'Histidine-rich glycoprotein': 10.37, 'Fibrinogen alpha chain': 0.96,
  },
  {
    id: 4, source: 'Cleaned_Proteins_Regression',
    mod_type: 'PEG', mod_charge: 'No Modification',
    np_type: 'Organic', np_sub_type: 'Lipid',
    size_group: '50~100', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_time_group: '<30',
    shaking: 'N', washing_step_count: '1~3',
    'Apolipoprotein A-I': 6.44, 'Complement C3': 0.88,
    'Apolipoprotein E': 1.92, 'Serum albumin': 3.10,
    'Clusterin': 1.02, 'Vitronectin': 0.55,
    'Histidine-rich glycoprotein': 4.22, 'Fibrinogen alpha chain': 0.61,
  },
  {
    id: 5, source: 'Cleaned_Proteins_Regression',
    mod_type: 'Carboxyl', mod_charge: 'Negative',
    np_type: 'Inorganic', np_sub_type: 'Metal',
    size_group: '<50', zp_solvent: 'Water', zp_group: '-10~0',
    zp_charge: 'Negative', incu_time_group: '>60',
    shaking: 'Y', washing_step_count: '4~6',
    'Apolipoprotein A-I': 2.10, 'Complement C3': 2.31,
    'Apolipoprotein E': 4.88, 'Serum albumin': 0.89,
    'Clusterin': 0.61, 'Vitronectin': 0.34,
    'Histidine-rich glycoprotein': 2.55, 'Fibrinogen alpha chain': 1.43,
  },
  {
    id: 6, source: 'Cleaned_Proteins_Regression',
    mod_type: 'No Modification', mod_charge: 'No Modification',
    np_type: 'Organic', np_sub_type: 'Polystyrene',
    size_group: '100~150', zp_solvent: 'PBS', zp_group: '0~10',
    zp_charge: 'Neutral', incu_time_group: '30~60',
    shaking: 'N', washing_step_count: '1~3',
    'Apolipoprotein A-I': 8.92, 'Complement C3': 1.55,
    'Apolipoprotein E': 3.21, 'Serum albumin': 2.78,
    'Clusterin': 0.88, 'Vitronectin': 1.12,
    'Histidine-rich glycoprotein': 7.66, 'Fibrinogen alpha chain': 0.28,
  },
  {
    id: 7, source: 'NP-PC_Database_Part_',
    mod_charge: 'No Modification',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '100~150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_protein_source: 'Human Plasma',
    plasma_conc_group: '50~100', incu_time_group: '30~60', shaking: 'Y',
    'Apolipoprotein A-I': 11.23, 'Complement C3': 1.09,
    'Apolipoprotein E': 5.19, 'Serum albumin': 1.31,
    'Clusterin': 0.24, 'Vitronectin': 1.39,
    'Histidine-rich glycoprotein': 10.31, 'Fibrinogen alpha chain': 0.37,
  },
  {
    id: 8, source: 'NP-PC_Database_Part_',
    mod_charge: 'No Modification',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '>150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_protein_source: 'Human Plasma',
    plasma_conc_group: '50~100', incu_time_group: '30~60', shaking: 'Y',
    'Apolipoprotein A-I': 7.17, 'Complement C3': 1.14,
    'Apolipoprotein E': 2.97, 'Serum albumin': 2.39,
    'Clusterin': 0.45, 'Vitronectin': 0.90,
    'Histidine-rich glycoprotein': 17.51, 'Fibrinogen alpha chain': 0.49,
  },
  {
    id: 9, source: 'NP-PC_Database_Part_',
    mod_charge: 'Positive',
    np_type: 'Inorganic', np_sub_type: 'Silica',
    size_group: '100~150', zp_solvent: 'PBS', zp_group: '-50~-10',
    zp_charge: 'Negative', incu_protein_source: 'Human Plasma',
    plasma_conc_group: '50~100', incu_time_group: '30~60', shaking: 'Y',
    'Apolipoprotein A-I': 3.77, 'Complement C3': 1.22,
    'Apolipoprotein E': 3.05, 'Serum albumin': 1.16,
    'Clusterin': 0.23, 'Vitronectin': 1.86,
    'Histidine-rich glycoprotein': 10.37, 'Fibrinogen alpha chain': 0.96,
  },
  {
    id: 10, source: 'NP-PC_Database_Part_',
    mod_charge: 'Negative',
    np_type: 'Organic', np_sub_type: 'Lipid',
    size_group: '50~100', zp_solvent: 'Serum', zp_group: '-10~0',
    zp_charge: 'Negative', incu_protein_source: 'Human Serum',
    plasma_conc_group: '50~100', incu_time_group: '>60', shaking: 'N',
    'Apolipoprotein A-I': 5.88, 'Complement C3': 0.74,
    'Apolipoprotein E': 2.11, 'Serum albumin': 4.05,
    'Clusterin': 1.34, 'Vitronectin': 0.67,
    'Histidine-rich glycoprotein': 3.19, 'Fibrinogen alpha chain': 0.52,
  },
  {
    id: 11, source: 'NP-PC_Database_Part_',
    mod_charge: 'No Modification',
    np_type: 'Carbon-Based', np_sub_type: 'Carbon',
    size_group: '<50', zp_solvent: 'PBS', zp_group: '-10~0',
    zp_charge: 'Neutral', incu_protein_source: 'Human Plasma',
    plasma_conc_group: '50~100', incu_time_group: '30~60', shaking: 'Y',
    'Apolipoprotein A-I': 4.32, 'Complement C3': 1.88,
    'Apolipoprotein E': 3.77, 'Serum albumin': 1.99,
    'Clusterin': 0.55, 'Vitronectin': 0.82,
    'Histidine-rich glycoprotein': 5.43, 'Fibrinogen alpha chain': 0.71,
  },
  {
    id: 12, source: 'Cleaned_Proteins_Regression',
    mod_type: 'PEG', mod_charge: 'No Modification',
    np_type: 'Inorganic', np_sub_type: 'Metal Oxide',
    size_group: '50~100', zp_solvent: 'Water', zp_group: '-10~0',
    zp_charge: 'Negative', incu_time_group: '30~60',
    shaking: 'Y', washing_step_count: '4~6',
    'Apolipoprotein A-I': 9.14, 'Complement C3': 0.96,
    'Apolipoprotein E': 4.43, 'Serum albumin': 1.74,
    'Clusterin': 0.38, 'Vitronectin': 1.05,
    'Histidine-rich glycoprotein': 8.88, 'Fibrinogen alpha chain': 0.44,
  },
]

export const NP_TYPES = ['Carbon-Based', 'Inorganic', 'Organic']
export const NP_SUB_TYPES = ['Carbon', 'DNA', 'Latex', 'Lipid', 'Metal', 'Metal Oxide', 'Niosome', 'Polystyrene', 'Protein', 'Silica']
export const ZP_CHARGES = ['Negative', 'Neutral', 'Positive']
export const SIZE_GROUPS = ['<50', '50~100', '100~150', '>150']
export const INCU_TIME_GROUPS = ['<30', '30~60', '>60']
export const SOURCES = ['Cleaned_Proteins_Regression', 'NP-PC_Database_Part_']

export const TOP_PROTEINS = [
  'Apolipoprotein A-I',
  'Complement C3',
  'Apolipoprotein E',
  'Serum albumin',
  'Clusterin',
  'Vitronectin',
  'Histidine-rich glycoprotein',
  'Fibrinogen alpha chain',
]